### ISSUE TITLE
Submit code as integration module to jsonld-java

### ISSUE THREAD

**Issue by ansell** [ismriv/jsonld-rdf2go#1]
Are you able (and would like to) to submit this code back to jsonld-java as an integration module in the same way as the sesame/jena/clerezza modules are now arranged in Tristans git repository?

**Comment by ismriv** [comment]
Sorry ansell for taking so long to get back to you. I was currently thinking to update this to the new version of Tristan's JSONLD implementation and then publish it on maven central. What you say makes sense, I'll update the code then and open a pull request to merge this together with Tristan's impl.

Let me know if you have any other suggestion/comment!

**Comment by ansell** [comment]
Sounds good to me.
